server:
  port: 8090

spring:
  application:
    name: knowledge-trail-api
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/knowledge-trail-system
    username: postgres
    password: postgres      
  jpa:
    hibernate.ddl-auto: update
    show-sql: true 
