server:
  port: 8090

spring:
  application:
    name: locations-management-api
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/locations-management-system
    username: postgres
    password: postgres      
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true 
